### PR TITLE
Add --delete_after_upload option, update documentation accordingly

### PR DESCRIPTION
**Pull request by domdomegg**
I've been using and testing these updated scripts for about an hour with no problems, but I am still not 100% certain and also it's pretty likely I haven't followed best practices at python programming as I'm pretty new to it, so please do check and amend it as needed :)

### CODE REVIEW

**Comment by jesolem** [comment]
@ybkuang should review this.

**Comment by ybkuang** [comment]
@domdomegg Thanks for the help here! This diverges from the master quite a bit. I will review this more closely and see how we can proceed with this.

**Comment by mprins** [comment]
This PR is long out of date and cannot be merged, it should be closed.

**Comment by jernejaMislej** [comment]
unfortunately this PR is not compatible with the new version of tools, thank you for contributing

**Pull request closed without merging**
