### PR TITLE
addded a delete on success parameter

### PR DESCRIPTION
**Pull request by bitnapper**
addded a delete on success parameter so that files which are successfully uploaded won't get moved to success/ but deleted instead when parameter '-d' is set.

### CODE REVIEW

**Comment by domdomegg** [comment]
Did this in #111

**Comment by ybkuang** [comment]
This and #111 have diverged quite a bit from the master branch (due to our late response). I will take a deeper look and suggest something.

**Comment by mprins** [comment]
This PR is long out of date and cannot be merged, it should be closed.

**Comment by jernejaMislej** [comment]
unfortunately this PR is not compatible with the new version of tools, thank you for contributing

**Pull request closed without merging**
