### PR TITLE
feat: cut sequences by max file size 2GB

### PR DESCRIPTION
**Pull request by ptpt**

### CODE REVIEW

**Comment by ChristopheVeber** [comment]
Hi @ptpt,
your above change has been included into mapillary_tools-0.10.2.
However it does not seem to work on my end: When I upload a Gopro video of 6.97GB using [mapillary_tools-0.10.2-win-64bit.exe](https://github.com/mapillary/mapillary_tools/releases/download/v0.10.2/mapillary_tools-0.10.2-win-64bit.exe)
the sequence is NOT cut into 2GB chunks.
How should I proceed?

**Comment by ptpt** [comment]
@ChristopheVeber No, this applies to images only. Have plan for video cut as well. Could you file an issue and put some thoughts there?

7GB GoPro videos might be fine. Go ahead and upload.

**Comment by ChristopheVeber** [comment]
Hi, I am happy to file a ticket ' Where can I do this?Am 17.06.2023 19:52 schrieb Tao Peng ***@***.***>:
@ChristopheVeber No, this applies to images only. Have plan for video cut as well. Could you file an issue and put some thoughts there?
7GB GoPro videos might be fine. Go ahead and upload.

**Comment by ChristopheVeber** [comment]
I found it: Is
https://github.com/mapillary/mapillary_tools/issues/636
fine for you?

**Pull request merged**
